#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

tmp_dir=$TARGET_ROOT/tmp/pig
mkdir -p $tmp_dir

PIG_DOWNLOAD_URL=http://mirror.reverse.net/pub/apache/pig/pig-0.16.0/pig-0.16.0.tar.gz
PIG_FILE=$(basename $PIG_DOWNLOAD_URL)
cached_tar="$DIB_IMAGE_CACHE/$PIG_FILE"
$TMP_HOOKS_PATH/bin/cache-url $PIG_DOWNLOAD_URL $cached_tar
sudo install -D -g root -o root -m 0644 $cached_tar $tmp_dir
